### ISSUE TITLE
react roadmap sisi

### ISSUE THREAD

**Issue by biantris** [biantris/braintris#380]
- https://sibelius.github.io/zettelkasten/learning-path/learning-path-react
- [ ] What is React props?
- [ ] What is React state?
- [ ] unidirectional data flow
- [ ] how to create a React component
- [ ] React hooks (useState, useEffect, and other basics ones)
- [ ] Effects
- [ ] How to handle event handlers (onClick)
- [ ] React Context - share state for a subtree
- [ ] Recoiljs
- [ ] How to refactor a class component to hooks
- [ ] Create React App
- [ ] Learn what is a bundler, and how to use webpack, rollback and new solutions like vite.
- [ ] Learn how to do data fetching using pure fetch with useEffect, using react-query, using relay
- [ ] Learn how to do forms using formik
- [ ] Learn how to handle navigation using react-router
- [ ] Learn how to test using testing-library and jest
- [ ] Learn how to code split
- [ ] Learn Suspense
- [ ] Learn ErrorBoundary
- [ ] Learn about virtual dom and optimization
- [ ] Learn how to type components using Typescript
- [ ] Learn how to sync state to some external data like localStorage, cookies, querystring
